/**
 * Share Modal Component
 * 
 * Manages file sharing with configurable permissions, expiration, and password protection.
 * Short URLs are generated by the backend for better UX, with fallback to long URLs if
 * backend is unavailable. IPFS's content-addressing means shares remain valid even if
 * the original uploader goes offline (as long as someone has pinned the content).
 */

import React, { useState, useEffect } from 'react';
import CloseIcon from '@rsuite/icons/Close';
import CopyIcon from '@rsuite/icons/Copy';
import LockRoundIcon from '@rsuite/icons/LockRound';
import ShareRoundIcon from '@rsuite/icons/ShareRound';
import WaitIcon from '@rsuite/icons/Wait';
import WarningRoundIcon from '@rsuite/icons/WarningRound';
import styles from '../styles/ShareModal.module.css';

interface ShareConfig {
  shareId: string;
  enabled: boolean;
  createdDate: number;
  createdBy: string;
  permission: 'viewer' | 'editor';
  expiryDate?: number;
  password?: string;
  accessCount?: number;
  lastAccessedDate?: number;
  shortCode?: string;
  shortUrl?: string;
}

/** A walt user resolved as an end-to-end encryption recipient. */
export interface EncryptedRecipient {
  id: string;
  email: string;
  /** Imported ECDH public key, opaque to the modal (passed back to the caller). */
  publicKey: CryptoKey;
}

interface ShareModalProps {
  fileName: string;
  isOpen: boolean;
  onClose: () => void;
  onShare: (permission: 'viewer' | 'editor', expiryDate?: number, password?: string) => Promise<string | null>;
  onDisableShare: () => Promise<boolean>;
  existingShare?: ShareConfig;
  isFolder?: boolean;
  /**
   * OPTIONAL end-to-end encrypted sharing. When BOTH are supplied the modal
   * shows a "Share encrypted with a walt user" block. Omitting them leaves the
   * existing link-sharing UI exactly as-is (so current callers/tests are unaffected).
   *
   * onResolveRecipient: email → recipient identity, or null if the email has no
   *   published walt identity (the modal surfaces that loudly — no fallback).
   * onShareEncrypted: encrypt + share the file to the resolved recipients.
   */
  onResolveRecipient?: (email: string) => Promise<EncryptedRecipient | null>;
  onShareEncrypted?: (recipients: EncryptedRecipient[]) => Promise<void>;
}

const ShareModal: React.FC<ShareModalProps> = ({
  fileName,
  isOpen,
  onClose,
  onShare,
  onDisableShare,
  existingShare,
  isFolder = false,
  onResolveRecipient,
  onShareEncrypted,
}) => {
  const [permission, setPermission] = useState<'viewer' | 'editor'>('viewer');
  const [expiryEnabled, setExpiryEnabled] = useState(false);
  const [expiryDays, setExpiryDays] = useState(7);
  const [passwordEnabled, setPasswordEnabled] = useState(false);
  const [password, setPassword] = useState('');
  const [shareLink, setShareLink] = useState('');
  const [shortLink, setShortLink] = useState('');
  const [isSharing, setIsSharing] = useState(false);
  const [copied, setCopied] = useState(false);
  const [shortCopied, setShortCopied] = useState(false);

  // --- End-to-end encrypted recipient sharing (optional block) --------------
  const encryptedSharingEnabled = !!onResolveRecipient && !!onShareEncrypted;
  const [recipientEmail, setRecipientEmail] = useState('');
  const [recipients, setRecipients] = useState<EncryptedRecipient[]>([]);
  const [isResolving, setIsResolving] = useState(false);
  const [resolveError, setResolveError] = useState<string | null>(null);
  const [isSharingEncrypted, setIsSharingEncrypted] = useState(false);
  const [encryptedShareDone, setEncryptedShareDone] = useState(false);

  const handleAddRecipient = async () => {
    if (!onResolveRecipient) return;
    const email = recipientEmail.trim();
    setResolveError(null);
    if (!email) {
      setResolveError('Enter an email address');
      return;
    }
    if (recipients.some((r) => r.email.toLowerCase() === email.toLowerCase())) {
      setResolveError('That recipient is already added');
      return;
    }
    setIsResolving(true);
    try {
      const resolved = await onResolveRecipient(email);
      if (!resolved) {
        // Loud, no fallback: we never share to an unverified/substituted key.
        setResolveError(`No walt identity found for "${email}"`);
        return;
      }
      setRecipients((prev) => [...prev, resolved]);
      setRecipientEmail('');
    } catch (error) {
      setResolveError(error instanceof Error ? error.message : 'Could not look up that recipient');
    } finally {
      setIsResolving(false);
    }
  };

  const handleRemoveRecipient = (id: string) => {
    setRecipients((prev) => prev.filter((r) => r.id !== id));
  };

  const handleShareEncrypted = async () => {
    if (!onShareEncrypted || recipients.length === 0) return;
    setIsSharingEncrypted(true);
    setResolveError(null);
    try {
      await onShareEncrypted(recipients);
      setEncryptedShareDone(true);
      setRecipients([]);
    } catch (error) {
      setResolveError(error instanceof Error ? error.message : 'Encrypted share failed');
    } finally {
      setIsSharingEncrypted(false);
    }
  };

  useEffect(() => {
    // Populate form with existing share settings if file is already shared
    if (existingShare?.enabled) {
      setPermission(existingShare.permission);
      setShareLink(getShareLink(existingShare.shareId));
      
      // Short link provides better UX for sharing
      if (existingShare.shortUrl) {
        setShortLink(existingShare.shortUrl);
      } else if (existingShare.shortCode) {
        const shortUrl = typeof window !== 'undefined' 
          ? `${window.location.origin}/s/${existingShare.shortCode}`
          : '';
        setShortLink(shortUrl);
      }
      
      if (existingShare.expiryDate) {
        setExpiryEnabled(true);
        const daysLeft = Math.ceil((existingShare.expiryDate - Date.now()) / (1000 * 60 * 60 * 24));
        setExpiryDays(Math.max(1, daysLeft));
      }
      
      if (existingShare.password) {
        setPasswordEnabled(true);
      }
    }
  }, [existingShare]);

  const getShareLink = (shareId: string) => {
    if (typeof window !== 'undefined') {
      return `${window.location.origin}/share/${shareId}`;
    }
    return '';
  };

  const handleShare = async () => {
    setIsSharing(true);
    try {
      const expiryDate = expiryEnabled 
        ? Date.now() + (expiryDays * 24 * 60 * 60 * 1000)
        : undefined;
      
      const pwd = passwordEnabled && password ? password : undefined;
      
      const shareId = await onShare(permission, expiryDate, pwd);
      
      if (shareId) {
        setShareLink(getShareLink(shareId));
      }
    } catch (error) {
      console.error('Share failed:', error);
      // Note: Error handling should be done by parent component
      throw error;
    } finally {
      setIsSharing(false);
    }
  };

  const handleDisableShare = async () => {
    if (confirm('Remove share link? This will make the file inaccessible to anyone with the link.')) {
      setIsSharing(true);
      try {
        await onDisableShare();
        setShareLink('');
      } catch (error) {
        console.error('Disable share failed:', error);
        // Note: Error handling should be done by parent component
        throw error;
      } finally {
        setIsSharing(false);
      }
    }
  };

  const copyLink = () => {
    navigator.clipboard.writeText(shareLink);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const copyShortLink = () => {
    if (shortLink) {
      navigator.clipboard.writeText(shortLink);
      setShortCopied(true);
      setTimeout(() => setShortCopied(false), 2000);
    }
  };

  if (!isOpen) return null;

  const isShared = existingShare?.enabled && shareLink;

  return (
    <div className={styles.overlay} onClick={onClose}>
      <div className={styles.modal} onClick={(e) => e.stopPropagation()}>
        <div className={styles.header}>
          <h2>Share &quot;{fileName}&quot;</h2>
          <button className={styles.closeBtn} onClick={onClose} aria-label="Close share modal">
            <CloseIcon />
          </button>
        </div>

        <div className={styles.content}>
          {isShared ? (
            <>
              {/* Existing Share */}
              <div className={styles.shareActive}>
                <div className={styles.shareInfo}>
                  <span className={styles.shareIcon} aria-hidden>
                    <ShareRoundIcon />
                  </span>
                  <div>
                    <div className={styles.shareLabel}>Share link is active</div>
                    <div className={styles.shareMeta}>
                      Permission: <strong>{permission}</strong>
                      {existingShare.accessCount !== undefined && (
                        <> • Accessed: <strong>{existingShare.accessCount} times</strong></>
                      )}
                    </div>
                    {existingShare.expiryDate && (
                      <div className={styles.shareExpiry}>
                        Expires: {new Date(existingShare.expiryDate).toLocaleDateString()}
                      </div>
                    )}
                  </div>
                </div>

                {shortLink && (
                  <div className={styles.linkBox} style={{ marginBottom: '1rem' }}>
                    <label className={`${styles.shareLabel} ${styles.labelWithIcon}`} style={{ marginBottom: '0.5rem', display: 'block' }}>
                      <ShareRoundIcon className={styles.inlineIcon} />
                      Short Link
                    </label>
                    <input 
                      type="text" 
                      value={shortLink} 
                      readOnly 
                      className={styles.linkInput}
                    />
                    <button 
                      className={styles.copyBtn}
                      onClick={copyShortLink}
                    >
                      {shortCopied ? (
                        'Copied!'
                      ) : (
                        <>
                          <CopyIcon className={styles.buttonIcon} />
                          Copy
                        </>
                      )}
                    </button>
                  </div>
                )}
                
                <div className={styles.linkBox}>
                  <label className={styles.shareLabel} style={{ marginBottom: '0.5rem', display: 'block' }}>
                    Full Share Link
                  </label>
                  <input 
                    type="text" 
                    value={shareLink} 
                    readOnly 
                    className={styles.linkInput}
                  />
                  <button 
                    className={styles.copyBtn}
                    onClick={copyLink}
                  >
                    {copied ? (
                      'Copied!'
                    ) : (
                      <>
                        <CopyIcon className={styles.buttonIcon} />
                        Copy
                      </>
                    )}
                  </button>
                </div>

                <button 
                  className={styles.disableBtn}
                  onClick={handleDisableShare}
                  disabled={isSharing}
                >
                  <LockRoundIcon className={styles.buttonIcon} />
                  Disable Sharing
                </button>
              </div>
            </>
          ) : (
            <>
              {/* Create New Share */}
              <div className={styles.section}>
                <label className={styles.label}>Permission Level</label>
                <select 
                  className={styles.select}
                  value={permission}
                  onChange={(e) => setPermission(e.target.value as 'viewer' | 'editor')}
                >
                  <option value="viewer">Viewer - Can view only</option>
                  <option value="editor">Editor - Can view and download</option>
                </select>
                <p className={styles.hint}>
                  {permission === 'viewer' 
                    ? 'Viewers can see the file but cannot download it'
                    : 'Editors can view and download the file'}
                </p>
              </div>

              <div className={styles.section}>
                <label className={styles.checkbox}>
                  <input 
                    type="checkbox"
                    checked={expiryEnabled}
                    onChange={(e) => setExpiryEnabled(e.target.checked)}
                  />
                  <span>Set expiration date</span>
                </label>
                {expiryEnabled && (
                  <div className={styles.expiryInput}>
                    <input 
                      type="number"
                      min="1"
                      max="365"
                      value={expiryDays}
                      onChange={(e) => setExpiryDays(parseInt(e.target.value) || 1)}
                      className={styles.numberInput}
                    />
                    <span>days from now</span>
                  </div>
                )}
              </div>

              <div className={styles.section}>
                <label className={styles.checkbox}>
                  <input 
                    type="checkbox"
                    checked={passwordEnabled}
                    onChange={(e) => setPasswordEnabled(e.target.checked)}
                  />
                  <span>Password protect</span>
                </label>
                {passwordEnabled && (
                  <input 
                    type="text"
                    placeholder="Enter password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    className={styles.textInput}
                  />
                )}
              </div>

              <div className={styles.warning}>
                <WarningRoundIcon className={styles.inlineIcon} />
                <span>
                  Anyone with the link will be able to {permission === 'viewer' ? 'view' : 'view and download'} this {isFolder ? 'folder' : 'file'}.
                </span>
              </div>

              <button 
                className={styles.shareBtn}
                onClick={handleShare}
                disabled={isSharing || (passwordEnabled && !password)}
              >
                {isSharing ? (
                  <>
                    <WaitIcon className={styles.buttonIcon} />
                    Creating...
                  </>
                ) : (
                  <>
                    <ShareRoundIcon className={styles.buttonIcon} />
                    Create Share Link
                  </>
                )}
              </button>
            </>
          )}

          {/* End-to-end encrypted sharing with a walt user (optional block). */}
          {encryptedSharingEnabled && (
            <div className={styles.section} data-testid="encrypted-share-section">
              <hr style={{ border: 0, borderTop: '1px solid #eee', margin: '1.25rem 0' }} />
              <label className={`${styles.label} ${styles.labelWithIcon}`}>
                <LockRoundIcon className={styles.inlineIcon} />
                Share end-to-end encrypted with a walt user
              </label>
              <p className={styles.hint}>
                The {isFolder ? 'folder' : 'file'} is encrypted to each recipient&apos;s key. Only they can
                decrypt it — the server never sees the contents.
              </p>

              <div style={{ display: 'flex', gap: '0.5rem', marginTop: '0.5rem' }}>
                <input
                  type="email"
                  placeholder="recipient@email.com"
                  value={recipientEmail}
                  onChange={(e) => {
                    setRecipientEmail(e.target.value);
                    setResolveError(null);
                  }}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      e.preventDefault();
                      handleAddRecipient();
                    }
                  }}
                  className={styles.textInput}
                  style={{ flex: 1 }}
                  aria-label="Recipient email"
                />
                <button
                  type="button"
                  className={styles.copyBtn}
                  onClick={handleAddRecipient}
                  disabled={isResolving}
                >
                  {isResolving ? 'Checking…' : 'Add recipient'}
                </button>
              </div>

              {resolveError && (
                <div className={styles.warning} role="alert" style={{ marginTop: '0.75rem' }}>
                  <WarningRoundIcon className={styles.inlineIcon} />
                  <span>{resolveError}</span>
                </div>
              )}

              {recipients.length > 0 && (
                <ul
                  style={{ listStyle: 'none', padding: 0, margin: '0.75rem 0 0', display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}
                  data-testid="recipient-chips"
                >
                  {recipients.map((r) => (
                    <li
                      key={r.id}
                      style={{
                        display: 'inline-flex',
                        alignItems: 'center',
                        gap: '0.4rem',
                        background: '#eef2ff',
                        color: '#3730a3',
                        borderRadius: '999px',
                        padding: '0.25rem 0.6rem',
                        fontSize: '0.85rem',
                      }}
                    >
                      <span aria-hidden>✓</span>
                      <span>{r.email}</span>
                      <button
                        type="button"
                        onClick={() => handleRemoveRecipient(r.id)}
                        aria-label={`Remove ${r.email}`}
                        style={{ background: 'none', border: 0, cursor: 'pointer', color: 'inherit', display: 'inline-flex' }}
                      >
                        <CloseIcon />
                      </button>
                    </li>
                  ))}
                </ul>
              )}

              {encryptedShareDone && (
                <p className={styles.hint} role="status" style={{ color: '#16a34a', marginTop: '0.75rem' }}>
                  Shared encrypted. Recipients will see it under &quot;Shared with you&quot;.
                </p>
              )}

              <button
                type="button"
                className={styles.shareBtn}
                onClick={handleShareEncrypted}
                disabled={isSharingEncrypted || recipients.length === 0}
                style={{ marginTop: '0.75rem' }}
              >
                {isSharingEncrypted ? (
                  <>
                    <WaitIcon className={styles.buttonIcon} />
                    Encrypting…
                  </>
                ) : (
                  <>
                    <LockRoundIcon className={styles.buttonIcon} />
                    Share encrypted
                  </>
                )}
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ShareModal;

